### ISSUE TITLE
How to check the navigation time for guides and followers?

### ISSUE THREAD

**Issue by VegB** [google-research-datasets/RxR#1]
Hi, I'm wondering how can I get to know how long it takes a guide/follower to reach the destination.

Currently, I'm using the `'time'` field in the pose trace, and I regard the last value in the time array as the time the guide/follower takes to finish the task.
I calculated the average time to finish the Follower task on the train set, and here's what I got on each language:

|                            | en-US | en-IN | hi-IN | te-IN |
| -------------------------- | ----- | ----- | ----- | ----- |
| avg time for Follower Task (seconds)| 105.0 | 68.7  | 89.3  | 79.6  |

I'm not sure if this is the correct practice, because the results in the table above are all smaller than the average time for the Follower tasks reported in the paper (132 seconds). 

It would be great if you can show me the correct way to receive the time-related information. Thanks!

**Comment by alexyku** [comment]
Hello,

The follower duration reported in the Table 2 represents the time it takes to complete the entire follower task -- reading the instructions, instruction following, and completing the survey. Figure 6 in the supplemental breaks it down and (d) should correspond to the time field in the pose trace.

Hope this helps!
