### ISSUE TITLE
"Timed Instruction" in RxR Dataset not consistent?

### ISSUE THREAD

**Issue by siddk** [google-research-datasets/RxR#2]
Hi! 

I've been trying to visualize the dataset via the code in `visualizations/first_person.html` but have run into a problem that I thought I should flag. It seems like in the original dataset (at least in `rxr_train`) some guide examples are missing the `"start_time"` and `"end_time"` fields in the `"timed_instruction"` list. 

For example, here are some broken instruction_ids (from rxr_train) that I found in just trying out the existing script:
- 10
- 12
- 55

**Comment by peteanderson80** [comment]
Thanks, there are a small number of words that don't have timing info. In that case it can be approximated from the neighbors. I've made a note of this in the readme.
