### ISSUE TITLE
Exact size of the dataset

### ISSUE THREAD

**Issue by shurjobanerjee** [google-research-datasets/RxR#3]
Hey! Could somebody provide the exact size of the dataset in TB on the README file? Would be helpful in planning the location of the download on our local systems.

**Comment by vamsikrishyvk** [comment]
It's 161.22 GiB , got that by running this command `gsutil du -sh gs://rxr-data/`

**Comment by shurjobanerjee** [comment]
Thank you!

**Comment by peteanderson80** [comment]
Great suggestion! I've added the sizes of each component to the readme.
