### ISSUE TITLE
Question about 'text_masks' in pose trace data

### ISSUE THREAD

**Issue by awesomericky** [google-research-datasets/RxR#4]
Hello,

I am curious about the feature in 'text_masks' in pose trace data.
I checked the data and found that the first word in instruction are always not masked while other words mask change in monotonic way which is reasonable as the agent progresses to the goal. Why is the first word in every viewpoint not masked?

![git_rxr](https://user-images.githubusercontent.com/58288696/110073556-e9870700-7dc2-11eb-8691-bbbcd2f44954.png)

**Comment by peteanderson80** [comment]
That is because we are using BERT tokenization and embeddings, so the first word is the CLS token which contains a representation for the entire instruction. We therefore decided to never mask that token.

**Comment by guhur** [comment]
Can you detail which tokenizer you employed? I tried with HF's BertTokenizer but I didn't obtain the same number of tokens as you. Thanks
