### ISSUE TITLE
Saving Visualizations as GIFs?

### ISSUE THREAD

**Issue by FelixLabelle** [google-research-datasets/RxR#5]
Is there a straight forward way of saving the guide trace visualizations like [first_person.gif](https://github.com/google-research-datasets/RxR/blob/main/visualizations/first_person.gif)? I imagine we could use three.js to do this, but any hints or code would be appreciated!

**Comment by peteanderson80** [comment]
From memory I think this was converted to gif from a video screen capture.

If you just need the camera view (not the text) it is relatively easy to capture and download a webm video from the canvas element that is rendering the first person view. An example can be found in this older [R2R annotation tool](https://github.com/peteanderson80/Matterport3DSimulator/blob/3295d16b1a124fcd14ceb3b22c79f332135300f1/web/app/js/Trajectory.js#L156).

**Comment by FelixLabelle** [comment]
Thanks, that does the trick!
